//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gwenchana.LanguagePack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gwenchana.LanguagePack.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deletion failed!.
        /// </summary>
        internal static string Account_Delete_Fail {
            get {
                return ResourceManager.GetString("Account_Delete_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted successfully!.
        /// </summary>
        internal static string Account_Delete_Success {
            get {
                return ResourceManager.GetString("Account_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account update failed!.
        /// </summary>
        internal static string Account_Edit_Fail {
            get {
                return ResourceManager.GetString("Account_Edit_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account updated successfully!.
        /// </summary>
        internal static string Account_Edit_Success {
            get {
                return ResourceManager.GetString("Account_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account updated successfully!.
        /// </summary>
        internal static string Account_Update_Success {
            get {
                return ResourceManager.GetString("Account_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have quit! Cannot log in to the app..
        /// </summary>
        internal static string Auth_Error_AccountInactive {
            get {
                return ResourceManager.GetString("Auth_Error_AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not authorized. Please contact Admin to be assigned..
        /// </summary>
        internal static string Auth_Error_InsufficientPermissions {
            get {
                return ResourceManager.GetString("Auth_Error_InsufficientPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect account or password!.
        /// </summary>
        internal static string Auth_Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists!.
        /// </summary>
        internal static string Auth_Error_UsernameExists {
            get {
                return ResourceManager.GetString("Auth_Error_UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful.
        /// </summary>
        internal static string Auth_Success_Registration {
            get {
                return ResourceManager.GetString("Auth_Success_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer parts/accessories.
        /// </summary>
        internal static string btn_Accessories {
            get {
                return ResourceManager.GetString("btn_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string btn_Accounts {
            get {
                return ResourceManager.GetString("btn_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string btn_Assign {
            get {
                return ResourceManager.GetString("btn_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Setting.
        /// </summary>
        internal static string btn_changeAccount {
            get {
                return ResourceManager.GetString("btn_changeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btn_changeInformation {
            get {
                return ResourceManager.GetString("btn_changeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string btn_customDate {
            get {
                return ResourceManager.GetString("btn_customDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string btn_Customers {
            get {
                return ResourceManager.GetString("btn_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string btn_Employees {
            get {
                return ResourceManager.GetString("btn_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btn_Exit {
            get {
                return ResourceManager.GetString("btn_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export invoices.
        /// </summary>
        internal static string btn_exportInvoices {
            get {
                return ResourceManager.GetString("btn_exportInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported invoices.
        /// </summary>
        internal static string btn_importInvoices {
            get {
                return ResourceManager.GetString("btn_importInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        internal static string btn_Invoices {
            get {
                return ResourceManager.GetString("btn_Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptops.
        /// </summary>
        internal static string btn_Laptops {
            get {
                return ResourceManager.GetString("btn_Laptops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 Days.
        /// </summary>
        internal static string btn_last30Days {
            get {
                return ResourceManager.GetString("btn_last30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        internal static string btn_last7Days {
            get {
                return ResourceManager.GetString("btn_last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        internal static string btn_PCs {
            get {
                return ResourceManager.GetString("btn_PCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string btn_personalInformation {
            get {
                return ResourceManager.GetString("btn_personalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string btn_Products {
            get {
                return ResourceManager.GetString("btn_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btn_Search {
            get {
                return ResourceManager.GetString("btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string btn_SignUp {
            get {
                return ResourceManager.GetString("btn_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string btn_Statistics {
            get {
                return ResourceManager.GetString("btn_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        internal static string btn_Suppliers {
            get {
                return ResourceManager.GetString("btn_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        internal static string btn_thisMonth {
            get {
                return ResourceManager.GetString("btn_thisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string btn_Today {
            get {
                return ResourceManager.GetString("btn_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string Confirm_Exit {
            get {
                return ResourceManager.GetString("Confirm_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm_Title {
            get {
                return ResourceManager.GetString("Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string dvg_Item {
            get {
                return ResourceManager.GetString("dvg_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string dvg_Units {
            get {
                return ResourceManager.GetString("dvg_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee has not resigned yet!.
        /// </summary>
        internal static string Employee_Error_NotResigned {
            get {
                return ResourceManager.GetString("Employee_Error_NotResigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employee found with name : .
        /// </summary>
        internal static string Employee_Search_NotFoundByName {
            get {
                return ResourceManager.GetString("Employee_Search_NotFoundByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all blank fields.
        /// </summary>
        internal static string Form_Validation_EmptyFields {
            get {
                return ResourceManager.GetString("Form_Validation_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account management.
        /// </summary>
        internal static string lb_accountManagement {
            get {
                return ResourceManager.GetString("lb_accountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string lb_Counter {
            get {
                return ResourceManager.GetString("lb_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string lb_CustomerCounter {
            get {
                return ResourceManager.GetString("lb_CustomerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age :.
        /// </summary>
        internal static string lb_employeeAge {
            get {
                return ResourceManager.GetString("lb_employeeAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        internal static string lb_employeeName {
            get {
                return ResourceManager.GetString("lb_employeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lb_employeeName1 {
            get {
                return ResourceManager.GetString("lb_employeeName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string lb_employeePassword {
            get {
                return ResourceManager.GetString("lb_employeePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lb_employeePassword1 {
            get {
                return ResourceManager.GetString("lb_employeePassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string lb_employeePhonenumber {
            get {
                return ResourceManager.GetString("lb_employeePhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string lb_employeeRole {
            get {
                return ResourceManager.GetString("lb_employeeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lb_employeeStatus {
            get {
                return ResourceManager.GetString("lb_employeeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username :.
        /// </summary>
        internal static string lb_employeeUsername {
            get {
                return ResourceManager.GetString("lb_employeeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lb_employeeUsername1 {
            get {
                return ResourceManager.GetString("lb_employeeUsername1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language :.
        /// </summary>
        internal static string lb_Language {
            get {
                return ResourceManager.GetString("lb_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login account.
        /// </summary>
        internal static string lb_Login {
            get {
                return ResourceManager.GetString("lb_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low inventory products.
        /// </summary>
        internal static string lb_lowIventory {
            get {
                return ResourceManager.GetString("lb_lowIventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string lb_Password {
            get {
                return ResourceManager.GetString("lb_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string lb_personalInformation {
            get {
                return ResourceManager.GetString("lb_personalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string lb_ProductCounter {
            get {
                return ResourceManager.GetString("lb_ProductCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search : .
        /// </summary>
        internal static string lb_Search {
            get {
                return ResourceManager.GetString("lb_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Store.
        /// </summary>
        internal static string lb_ShopName {
            get {
                return ResourceManager.GetString("lb_ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string lb_ShowPassword {
            get {
                return ResourceManager.GetString("lb_ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for an account.
        /// </summary>
        internal static string lb_SignUp {
            get {
                return ResourceManager.GetString("lb_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string lb_Statistics {
            get {
                return ResourceManager.GetString("lb_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string lb_SupplierCounter {
            get {
                return ResourceManager.GetString("lb_SupplierCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total profit.
        /// </summary>
        internal static string lb_TotalProfit {
            get {
                return ResourceManager.GetString("lb_TotalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total revenue.
        /// </summary>
        internal static string lb_TotalRevenue {
            get {
                return ResourceManager.GetString("lb_TotalRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sales orders.
        /// </summary>
        internal static string lb_TotalSalesOrders {
            get {
                return ResourceManager.GetString("lb_TotalSalesOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username :.
        /// </summary>
        internal static string lb_Username {
            get {
                return ResourceManager.GetString("lb_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment failed.
        /// </summary>
        internal static string Permission_Assign_Fail {
            get {
                return ResourceManager.GetString("Permission_Assign_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment successful.
        /// </summary>
        internal static string Permission_Assign_Success {
            get {
                return ResourceManager.GetString("Permission_Assign_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization status.
        /// </summary>
        internal static string Permission_Assignment_Status {
            get {
                return ResourceManager.GetString("Permission_Assignment_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to return to login?.
        /// </summary>
        internal static string Prompt_ConfirmReturnToLogin {
            get {
                return ResourceManager.GetString("Prompt_ConfirmReturnToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string TabCtr_Details {
            get {
                return ResourceManager.GetString("TabCtr_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string TabCtr_List {
            get {
                return ResourceManager.GetString("TabCtr_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 best selling products.
        /// </summary>
        internal static string txt_Top5product {
            get {
                return ResourceManager.GetString("txt_Top5product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total revenue.
        /// </summary>
        internal static string txt_Totalrevenue {
            get {
                return ResourceManager.GetString("txt_Totalrevenue", resourceCulture);
            }
        }
    }
}
